### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by kprasadvnsi** [thirtythreeforty/businesscard-linux#10]
![Screenshot at 2020-01-05 16-37-25](https://user-images.githubusercontent.com/3696543/71779694-657a9900-2fde-11ea-9d23-78af85c49514.png)

It failed the same way everytime.

**Comment by thirtythreeforty** [comment]
Hmm that's weird... it [works in CI](https://github.com/thirtythreeforty/businesscard-linux/actions) on a clean Ubuntu 18.04 image. What happens if you `make fortune-mod-dirclean host-fortune-mod-dirclean all`?

**Comment by kprasadvnsi** [comment]
`kp@vivobook:~/trials/businesscard-linux/buildroot$ make fortune-mod-dirclean host-fortune-mod-dirclean all
rm -Rf /home/kp/trials/businesscard-linux/buildroot/output/build/fortune-mod-2.10.0
rm -Rf /home/kp/trials/businesscard-linux/buildroot/output/build/host-fortune-mod-2.10.0
WARNING: no hash file for fortune-mod-2.10.0.tar.gz
>>> host-fortune-mod 2.10.0 Extracting
gzip -d -c /home/kp/trials/businesscard-linux/buildroot/dl/fortune-mod/fortune-mod-2.10.0.tar.gz | tar --strip-components=1 -C /home/kp/trials/businesscard-linux/buildroot/output/build/host-fortune-mod-2.10.0   -xf -
>>> host-fortune-mod 2.10.0 Patching

Applying 0001-host-strfile.patch using patch: 
patching file fortune-mod/datfiles/CMakeLists.txt

Applying 0002-custom-cookies.patch using patch: 
patching file fortune-mod/CMakeLists.txt

Applying 0003-fortune-in-usr-bin.patch using patch: 
patching file fortune-mod/CMakeLists.txt
>>> host-fortune-mod 2.10.0 Configuring
(mkdir -p /home/kp/trials/businesscard-linux/buildroot/output/build/host-fortune-mod-2.10.0/fortune-mod/buildroot-build && cd /home/kp/trials/businesscard-linux/buildroot/output/build/host-fortune-mod-2.10.0/fortune-mod/buildroot-build && rm -f CMakeCache.txt && PATH="/home/kp/trials/businesscard-linux/buildroot/output/host/bin:/home/kp/trials/businesscard-linux/buildroot/output/host/sbin:/home/kp/apps/android/platform-tools:/home/kp/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/kp/apps/go/bin:/home/kp/apps/libwebp-1.1.0-rc2-linux-x86-64/bin:/home/kp/trials/f1c100s/toolchain/gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabi/bin" PKG_CONFIG="/home/kp/trials/businesscard-linux/buildroot/output/host/bin/pkg-config" PKG_CONFIG_SYSROOT_DIR="/" PKG_CONFIG_LIBDIR="/home/kp/trials/businesscard-linux/buildroot/output/host/lib/pkgconfig:/home/kp/trials/businesscard-linux/buildroot/output/host/share/pkgconfig" PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 PKG_CONFIG_ALLOW_SYSTEM_LIBS=1  /home/kp/trials/businesscard-linux/buildroot/output/host/bin/cmake /home/kp/trials/businesscard-linux/buildroot/output/build/host-fortune-mod-2.10.0/fortune-mod -DCMAKE_INSTALL_SO_NO_EXE=0 -DCMAKE_FIND_ROOT_PATH="/home/kp/trials/businesscard-linux/buildroot/output/host" -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM="BOTH" -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY="BOTH" -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE="BOTH" -DCMAKE_INSTALL_PREFIX="/home/kp/trials/businesscard-linux/buildroot/output/host" -DCMAKE_C_FLAGS="-O2 -I/home/kp/trials/businesscard-linux/buildroot/output/host/include" -DCMAKE_CXX_FLAGS="-O2 -I/home/kp/trials/businesscard-linux/buildroot/output/host/include" -DCMAKE_EXE_LINKER_FLAGS="-L/home/kp/trials/businesscard-linux/buildroot/output/host/lib -Wl,-rpath,/home/kp/trials/businesscard-linux/buildroot/output/host/lib" -DCMAKE_SHARED_LINKER_FLAGS="-L/home/kp/trials/businesscard-linux/buildroot/output/host/lib -Wl,-rpath,/home/kp/trials/businesscard-linux/buildroot/output/host/lib" -DCMAKE_ASM_COMPILER="/usr/bin/as" -DCMAKE_C_COMPILER="/home/kp/trials/businesscard-linux/buildroot/output/host/bin/ccache" -DCMAKE_CXX_COMPILER="/home/kp/trials/businesscard-linux/buildroot/output/host/bin/ccache"  -DCMAKE_C_COMPILER_ARG1="/usr/bin/gcc" -DCMAKE_CXX_COMPILER_ARG1="/usr/bin/g++"  -DCMAKE_COLOR_MAKEFILE=OFF -DBUILD_DOC=OFF -DBUILD_DOCS=OFF -DBUILD_EXAMPLE=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TEST=OFF -DBUILD_TESTS=OFF -DBUILD_TESTING=OFF   )
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /home/kp/trials/businesscard-linux/buildroot/output/host/bin/ccache
-- Check for working C compiler: /home/kp/trials/businesscard-linux/buildroot/output/host/bin/ccache -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/kp/trials/businesscard-linux/buildroot/output/host/bin/ccache
-- Check for working CXX compiler: /home/kp/trials/businesscard-linux/buildroot/output/host/bin/ccache -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at cmake/shlomif_common_bootstrap.cmake:7 (MESSAGE):
  Could not find Shlomif_Common.cmake - you can find it here:
  https://bitbucket.org/shlomif/shlomif-cmake-modules/overview ; trying to
  download it for you.
Call Stack (most recent call first):
  CMakeLists.txt:3 (INCLUDE)


CMake Error at CMakeLists.txt:4 (SHLOMIF_COMMON_SETUP):
  Unknown CMake command "SHLOMIF_COMMON_SETUP".


-- Configuring incomplete, errors occurred!
See also "/home/kp/trials/businesscard-linux/buildroot/output/build/host-fortune-mod-2.10.0/fortune-mod/buildroot-build/CMakeFiles/CMakeOutput.log".
package/pkg-generic.mk:228: recipe for target '/home/kp/trials/businesscard-linux/buildroot/output/build/host-fortune-mod-2.10.0/.stamp_configured' failed
make[1]: *** [/home/kp/trials/businesscard-linux/buildroot/output/build/host-fortune-mod-2.10.0/.stamp_configured] Error 1
Makefile:84: recipe for target '_all' failed
make: *** [_all] Error 2
`

**Comment by thirtythreeforty** [comment]
Well, one thing you could do is deselect the package in menuconfig (`make menuconfig`). I think it's under an "external packages" section.

**Comment by kprasadvnsi** [comment]
now it builds. thanks
