### ISSUE TITLE
Unknown CMake command "SHLOMIF_COMMON_SETUP"

### ISSUE THREAD

**Issue by KrystofVydra** [thirtythreeforty/businesscard-linux#17]
hello, I am having troubles with the make command when building the buildroot from your repo.  
This is output of the make command at the end: 

```
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at cmake/shlomif_common_bootstrap.cmake:7 (MESSAGE):
  Could not find Shlomif_Common.cmake - you can find it here:
  https://bitbucket.org/shlomif/shlomif-cmake-modules/overview ; trying to
  download it for you.
Call Stack (most recent call first):
  CMakeLists.txt:3 (INCLUDE)


CMake Error at CMakeLists.txt:4 (SHLOMIF_COMMON_SETUP):
  Unknown CMake command "SHLOMIF_COMMON_SETUP".


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/businesscard-linux/buildroot/output/build/host-fortune-mod-2.10.0/fortune-mod/buildroot-build/CMakeFiles/CMakeOutput.log".
make[1]: *** [package/pkg-generic.mk:231: /home/ubuntu/businesscard-linux/buildroot/output/build/host-fortune-mod-2.10.0/.stamp_configured] Error 1
make: *** [Makefile:84: _all] Error 2
```

I tried some googling of that CMake error and the only thing I found was that I need to include Shlomif_Common.cmake to cmake Modules folder. I did that (included it to `/businesscard-linux/buildroot/output/host/share/cmake-3.8/Modules` destination) but the make command is still giving me the same error. Do you have any ideas? I am kinda new to this.

**Comment by thirtythreeforty** [comment]
I am not sure what's causing this problem, it works for me and works in CI. Sorry!

It's being tracked in #15; head over there for details. Basically the workaround is to turn off the package.

**Comment by KrystofVydra** [comment]
Alright, I will try it today. (Now I saw the same issue already addressed in closed issues, my bad that I didn't saw it before, sorry for wasting your time)
