### ISSUE TITLE
could you provide the pcb file?

### ISSUE THREAD

**Issue by zhangguanzhang** [thirtythreeforty/businesscard-linux#2]
I need this to generate pcb

**Comment by thirtythreeforty** [comment]
Hello - thanks for your interest!

I haven't released the KiCAD design files and I don't plan to right now.  They're not terribly cleaned up anyway, and I am not yet finished tinkering with the design.

That said, my [KiCAD parts library](https://github.com/thirtythreeforty/3340_kicad) does provide the F1C100s symbol and footprint if you're hoping to draw your own, and my [blog post](http://localhost:1313/posts/2019/12/my-business-card-runs-linux/) about the business card provides the schematic.

I'm going to go ahead and close this issue, but feel free to reopen if you have other questions.
