### ISSUE TITLE
f1c200s

### ISSUE THREAD

**Issue by YuanChenMang** [thirtythreeforty/businesscard-linux#3]
If you can use f1c200s, it's perfect.
Without changing anything, the RAM is doubled.
Full 64MByte, excited

**Comment by thirtythreeforty** [comment]
I am considering buying some and experimenting. I believe they would drop in with a single device tree change (RAM size).

The difficulty is that they take a long time to ship to me from Taobao!

**Comment by thirtythreeforty** [comment]
Allwinner has gotten in touch with me and kindly provided some F1C200s samples.  I will report back with progress!

**Comment by jordanhenderson** [comment]
@thirtythreeforty Is there any possibility of sampling these boards? They look perfect for an application I am working on. Would appreciate knowing how to get in touch with Allwinner.

**Comment by thirtythreeforty** [comment]
@jordanhenderson I think you're unlikely to make much progress with them unless your quantities are very large - min order qty of the F1C100s thru their distributors is 1760 (!).

These are bare parts, not boards. If you have a design drawn up, shoot me an email and we can get you a few of my samples to play with.

**Comment by YuanChenMang** [comment]
I can help if you need it, I can buy any number of 100s and 200s at a relatively affordable price . 
Because I was also using 200s for open source hardware. : )

**Comment by thirtythreeforty** [comment]
@YuanChenMang That's awesome :) I may hit you up at some point.

I've soldered up a card with the F1C200s and I can confirm that it's a drop-in replacement for the F1C100s.  Linux auto-detects the increased RAM, so the same image works with both parts.

I'm writing a quick blog post about it; I'll link it here when it's live.

**Comment by thirtythreeforty** [comment]
https://www.thirtythreeforty.net/posts/2020/02/trying-the-allwinner-f1c200s/

I'm gonna go ahead and close this issue but feel free to keep the discussion going.
