### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by kg9316** [thirtythreeforty/businesscard-linux#4]
Great project !

I have already redrawn it in EasyEda ready to order.
It would have great to have your BOM with part numbers and suppliers.

Thanks

**Comment by thirtythreeforty** [comment]
You'll have to be creative with sourcing the F1C100s. I bought mine from Taobao.  Everything else I bought from LCSC and are really just jellybean. I think I call out all the relevant specs for the parts.

If you really have a board drawn, I'd be happy to send you

**Comment by kg9316** [comment]
Thanks for the offer, that's really kind of you :-)
I will contact you via email. 

The only thing I need to get right before I place the PCB order is the crystal (same question as @MrWeng in another issue)

I have also ordered a couple of LicheePi Nano development boards from seeedstudio.com to play around with. Only 4 days in mail from China to Norway is impressive! (sent with DHL express)
