### ISSUE TITLE
about build tools

### ISSUE THREAD

**Issue by darkgirl** [thirtythreeforty/businesscard-linux#5]
hi,
I like this project.
and I am trying to build it.
I noticed that it need to download a lot of tools and build them. it is great because i would not install a lot of tools to my system.
but sometime i would like to build it without network, and my system already installed build tools.
how can i use my system tool rather than download and build them.

Thanks for you patient

**Comment by thirtythreeforty** [comment]
I'd look at the Buildroot user manual - https://buildroot.org/downloads/manual/manual.html. It's possible to use a system toolchain, if that's what you're asking.

If you're hoping to reuse the applications installed on your system and put them onto the card, that is not going to work for several different reasons. You will need to compile code explicitly for the card.

**Comment by darkgirl** [comment]
ok, thank you.
and when i build the project , i got an error:
Saving to: ‘/home/***/share/businesscard-linux/buildroot/output/build/.gcc-8.3.0.tar.xz.VyUIkd/output’

/home/***/share/businesscard-linux/buildr 100%[===================================================================================================>]  60.74M   806KB/s    in 58s     

2019-12-27 12:28:01 (1.04 MB/s) - ‘/home/***/share/businesscard-linux/buildroot/output/build/.gcc-8.3.0.tar.xz.VyUIkd/output’ saved [63694700/63694700]

ERROR: No hash found for gcc-8.3.0.tar.xz
make[1]: *** [package/pkg-generic.mk:146: /home/***/share/businesscard-linux/buildroot/output/build/host-gcc-initial-8.3.0/.stamp_downloaded] Error 1
make: *** [Makefile:84: _all] Error 2

it looks like buildroot went wrong, but i am not familiar with buildroot, and they do not have git issue.
can you help me ask about it, i searched  from the internet and got nothing about it.
thank you very much

**Comment by darkgirl** [comment]
hi,
actually, after i wrote last comment, i tried to solve this problem.
after i run following command
find ./ -name gcc*
I found something useful, and after trying to run the following command, it worked:
cp package/gcc/gcc.hash package/gcc/gcc-initial/gcc-initial.hash

but then i got several similar error, i have to run these similar command:
cp linux/linux.hash package/linux-headers/linux-headers.hash
cp package/gcc/gcc.hash package/gcc/gcc-final/gcc-final.hash
 
maybe this would help
