### ISSUE TITLE
About the use of crystal

### ISSUE THREAD

**Issue by MrWeng** [thirtythreeforty/businesscard-linux#6]
Hi guys, thank you for providing such an excellent project. When I was designing the schematic, I didn't know if the 24MHz you used was active or passive? please tell me，thanks

**Comment by MrWeng** [comment]
If yes, please tell me the model of the crystal, manufacturer, thank you

**Comment by thirtythreeforty** [comment]
The crystal I'm using is passive (hence the connection to CLKO).  I'd like to emphasize that **most 24MHz crystals will work**, and you'll just adjust the tuning capacitors according to the load specified.

I used a [Yangxing X322524MPB4SI](https://lcsc.com/product-detail/SMD-Crystal-Resonators_Yangxing-Tech-X322524MPB4SI_C113670.html) crystal, which has a very standard footprint and is very cost-effective.
