### ISSUE TITLE
Build error: "You have legacy configuration in your .config"

### ISSUE THREAD

**Issue by Chrithon** [thirtythreeforty/businesscard-linux#8]
Makefile.legacy:9: *** "You have legacy configuration in your .config! Please check your configuration."。 停止。
make: *** [Makefile:84：_all] 错误 2
chris@chris-MS-7B22:~/myboard/businesscard-linux/buildroot$

**Comment by Chrithon** [comment]
Result：
You have legacy configuration in your .config! Please check your configuration.

**Comment by thirtythreeforty** [comment]
Are you using Buildroot 2019.05.1?  If you've checked out a newer version, some of the config options could have been deprecated.  Post the output of `git describe` in your `buildroot` directory.

**Comment by thirtythreeforty** [comment]
`master` compiles in GitHub Actions CI, so I'm going to go ahead and close this.  Please leave comments if you continue to have trouble!
