### ISSUE TITLE
Polyfuse

### ISSUE THREAD

**Issue by xiaoyaowudi-extreme** [thirtythreeforty/businesscard-linux#9]
May I know the parameters of the polyfuse?

**Comment by thirtythreeforty** [comment]
Currently all the ones I have built have simply had a 0-ohm resistor there.  I put that in for a combination of the option of having a fuse, and being able to measure current consumption.  I have not done the latter, so I can't tell you current consumption unfortunately.  Likely it would be similar to that of the Lichee Nano.

**Comment by xiaoyaowudi-extreme** [comment]
Thanks.
